### ISSUE TITLE
数据预处理的时候出现问题，找不到错误原因了

### ISSUE THREAD

**Issue by aazyk** [taishan1994/pytorch_bert_bilstm_crf_ner#10]
![75f4b83ae597b43d3ad45e8421bb7f5](https://user-images.githubusercontent.com/71811610/165759769-ec835fb6-3fd3-4afb-93bb-c98ea3440fc2.png)
我是按照您提供的数据格式进行添加，但是在数据预处理的时候遇到了问题，不知道应该怎么修改，希望您能进行解答！万分感谢！

**Comment by taishan1994** [comment]
> ![75f4b83ae597b43d3ad45e8421bb7f5](https://user-images.githubusercontent.com/71811610/165759769-ec835fb6-3fd3-4afb-93bb-c98ea3440fc2.png) 我是按照您提供的数据格式进行添加，但是在数据预处理的时候遇到了问题，不知道应该怎么修改，希望您能进行解答！万分感谢！

你是运行的raw_data下的process.py么？

**Comment by taishan1994** [comment]
> > > ![75f4b83ae597b43d3ad45e8421bb7f5](https://user-images.githubusercontent.com/71811610/165759769-ec835fb6-3fd3-4afb-93bb-c98ea3440fc2.png)我是按照您提供的数据格式添加的，但是在数据发送的时候遇到问题，不应该怎么修改，希望您能知道！万分感谢！
> > 
> > 
> > 你正在运行的 raw_data 下的 process.py 么？
> 
> 是的，运行的是这个文件

我刚克隆下来跑了下，没有出现问题额

**Comment by aazyk** [comment]
> > > > ![75f4b83ae597b43d3ad45e8421bb7f5](https://user-images.githubusercontent.com/71811610/165759769-ec835fb6-3fd3-4afb-93bb-c98ea3440fc2.png)我是按照您提供的数据格式添加的，但是在数据发送的时候遇到问题，不应该怎么修改，希望您能知道！万分感谢！
> > > 
> > > 
> > > 你正在运行的 raw_data 下的 process.py 么？
> > 
> > 
> > 是的，运行的是这个文件
> 
> 我刚克隆下来跑了下，没有出现问题额

我百度了一下错误的提示原因，说是由于re匹配时在语料中存在特殊字符（由于语料特性，需要保留原语料字符格式）导致的，不知需要怎样修改呢，在re.finditer()时出现错误

**Comment by taishan1994** [comment]
> > > > > ![75f4b83ae597b43d3ad45e8421bb7f5](https://user-images.githubusercontent.com/71811610/165759769-ec835fb6-3fd3-4afb-93bb-c98ea3440fc2.png)我是按照您提供的数据格式添加的，但是在数据发送的时候遇到问题，不应该怎么修改，希望您能知道！万分感谢！
> > > > 
> > > > 
> > > > 你正在运行的 raw_data 下的 process.py 么？
> > > 
> > > 
> > > 是的，运行的是这个文件
> > 
> > 
> > 我刚克隆下来跑了下，没有出现问题额
> 
> 我百度了一下错误的提示原因，说是由于re匹配时在语料中存在特殊字符（由于语料特性，需要保留原语料字符格式）导致的，不知需要怎样修改呢，在re.finditer()时出现错误

将文本中的()[].*?都转义再匹配，比如re.sub('(','\(', text)等
