### ISSUE TITLE
--use_crf='True'报错

### ISSUE THREAD

**Issue by fishLucky7** [taishan1994/pytorch_bert_bilstm_crf_ner#11]
代码能跑通，但是设置--use_crf='True'后报错 __init__() got an unexpected keyword argument 'batch_first'，请问怎么解决？

**Comment by taishan1994** [comment]
> 代码能跑通，但是设置--use_crf='True'后报错 **init**() got an unexpected keyword argument 'batch_first'，请问怎么解决？

pytorch_crf的版本不对，使用pytorch_crf==0.7.2
