### ISSUE TITLE
关于数据集的问题

### ISSUE THREAD

**Issue by Lz6669** [taishan1994/pytorch_bert_bilstm_crf_ner#12]
您好 我的数据集的标注格式是BIO，请问怎么修改您的代码才能识别BIO格式的数据集呢？
万分感谢！

**Comment by Lz6669** [comment]
作者您好，我在您这个代码的时候，在验证步骤时报错
错误是：ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1
我查了一下是维度不匹配 在main.py文件中的第78行 
batch_output_all = np.append(batch_output_all, batch_output, axis=0)  这一行代码
请问怎么修改才能正常进行验证步骤呢？
万分感谢！

**Comment by taishan1994** [comment]
> 您好 我的数据集的标注格式是BIO，请问怎么修改您的代码才能识别BIO格式的数据集呢？ 万分感谢！

新建一个process.py，转换数据为mid_data下面的格式。

**Comment by taishan1994** [comment]
> 作者您好，我在您这个代码的时候，在验证步骤时报错 错误是：ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 我查了一下是维度不匹配 在main.py文件中的第78行 batch_output_all = np.append(batch_output_all, batch_output, axis=0) 这一行代码 请问怎么修改才能正常进行验证步骤呢？ 万分感谢！

下载最新的代码试试。
