### ISSUE TITLE
关于预训练语言模型

### ISSUE THREAD

**Issue by 17478020** [taishan1994/pytorch_bert_bilstm_crf_ner#15]
我换了一个model_type是roberta的预训练语言模型，结果代码就报错了，请问下这是为什么，可以怎么解决？
![Uploading image.png…]()

**Comment by 17478020** [comment]
![image](https://user-images.githubusercontent.com/63388342/185558340-e4447e94-30e1-4350-95a3-6b8c1ec6b670.png)

**Comment by 17478020** [comment]
![image](https://user-images.githubusercontent.com/63388342/185558495-4ab4e2c2-0d0f-4c75-a447-e2054cfb4f94.png)

**Comment by taishan1994** [comment]
> ![image](https://user-images.githubusercontent.com/63388342/185558495-4ab4e2c2-0d0f-4c75-a447-e2054cfb4f94.png)

用的哪一个roberta

**Comment by 17478020** [comment]
不好意思，可能是我自己搞错了吗，麻烦了，已解决。
