### ISSUE TITLE
我在这个包里面没有找到final_data的处理文件

### ISSUE THREAD

**Issue by LDLINGLINGLING** [taishan1994/pytorch_bert_bilstm_crf_ner#16]
请问这个final_data的处理文件在哪里，或者说是怎么处理所得到的？

**Comment by taishan1994** [comment]
> 请问这个final_data的处理文件在哪里，或者说是怎么处理所得到的？

preprocess.py里面设置数据集名及文本最大长度，然后按照例子运行即可生成final_data下的文件。
