### ISSUE TITLE
名称错误

### ISSUE THREAD

**Issue by shallowime** [taishan1994/pytorch_bert_bilstm_crf_ner#18]
![image](https://user-images.githubusercontent.com/51881265/191402598-be619849-7440-48ee-a985-b90c07f815b4.png)

**Comment by taishan1994** [comment]
> ![image](https://user-images.githubusercontent.com/51881265/191402598-be619849-7440-48ee-a985-b90c07f815b4.png)

感谢指出，可能之前忘了改了，已修改。
