### ISSUE TITLE
多GPU训练出错

### ISSUE THREAD

**Issue by Homura1212** [taishan1994/pytorch_bert_bilstm_crf_ner#19]
用了0和3号两张卡，报错信息如下：
"RuntimeError: Input and hidden tensors are not at the same device, found input tensor at cuda:3 and hidden tensor at cuda:0"

**Comment by taishan1994** [comment]
> 用了0和3号两张卡，报错信息如下： "RuntimeError: Input and hidden tensors are not at the same device, found input tensor at cuda:3 and hidden tensor at cuda:0"

只支持单卡训练额。

**Comment by Homura1212** [comment]
好吧，我看有预留接口以为是可以多卡的，尝试改了好几个地方都还是一样的报错。
