### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by 17478020** [taishan1994/pytorch_bert_bilstm_crf_ner#20]
您好，我换了一个数据集之后就出现这个问题，请问是代码里没有对句子进行补全操作吗？
![image](https://user-images.githubusercontent.com/63388342/192083871-be5581d3-fd8e-42b6-b028-58a97228a8d4.png)

**Comment by taishan1994** [comment]
> 您好，我换了一个数据集之后就出现这个问题，请问是代码里没有对句子进行补全操作吗？ ![image](https://user-images.githubusercontent.com/63388342/192083871-be5581d3-fd8e-42b6-b028-58a97228a8d4.png)

是有的，看看你这是不是标签数目的问题。
