### ISSUE TITLE
执行问题

### ISSUE THREAD

**Issue by aazyk** [taishan1994/pytorch_bert_bilstm_crf_ner#21]
您好！
        我调试您的代码，跑程序之后，程序跑不起来，不知是否是我的命令错误？
<img width="596" alt="b06329b4c8786d09d5c4c3daa0c6a56" src="https://user-images.githubusercontent.com/71811610/194717357-2bf993cd-f24f-48c9-9dc4-b4275dc96b0a.png">

**Comment by taishan1994** [comment]
> 您好！ 我调试您的代码，跑程序之后，程序跑不起来，不知是否是我的命令错误？ <img alt="b06329b4c8786d09d5c4c3daa0c6a56" width="596" src="https://user-images.githubusercontent.com/71811610/194717357-2bf993cd-f24f-48c9-9dc4-b4275dc96b0a.png">

后面的参数没有带上。
