### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by suaverjt** [taishan1994/pytorch_bert_bilstm_crf_ner#23]
你好作者，请问我按照您的步骤main.py文件运行后什么结果也没有，直接结束进程了，不知道是什么原因。另外在preprocess.py运行结果中出现这结果是正常的吗？
<img width="593" alt="2" src="https://user-images.githubusercontent.com/105686277/196043649-b263d0ea-cb16-4e7f-ad3d-04b80e888dc4.png">
<img width="724" alt="1" src="https://user-images.githubusercontent.com/105686277/196043605-f4f8477c-2b7d-428f-83f2-56b437fa1b89.png">

**Comment by taishan1994** [comment]
> 你好作者，请问我按照您的步骤main.py文件运行后什么结果也没有，直接结束进程了，不知道是什么原因。另外在preprocess.py运行结果中出现这结果是正常的吗？ <img alt="2" width="593" src="https://user-images.githubusercontent.com/105686277/196043649-b263d0ea-cb16-4e7f-ad3d-04b80e888dc4.png"> <img alt="1" width="724" src="https://user-images.githubusercontent.com/105686277/196043605-f4f8477c-2b7d-428f-83f2-56b437fa1b89.png">

运行preprocess.py是正常的，在main.py里面对应数据集里面有训练、测试和预测代码，看看是不是有些注释掉了，将它们打开。另外最好在命令行运行main.py，带上参数，不要直接在pycharm里面运行。

**Comment by suaverjt** [comment]
另外我想请教一下我在main.sh里修改是否使用crf或者lstm，运行时没有变化是什么问题？

**Comment by taishan1994** [comment]
> 另外我想请教一下我在main.sh里修改是否使用crf或者lstm，运行时没有变化是什么问题？

运行的指令是什么样子，发出来看看。
