### ISSUE TITLE
缺少args.json及网盘中的模型文件是CHIP2020的模型吗

### ISSUE THREAD

**Issue by kyla1994** [taishan1994/pytorch_bert_bilstm_crf_ner#25]

**Comment by taishan1994** [comment]
> 您好，请问可以给args.json吗？以及网盘中的模型文件是CHIP2020的模型吗？

我都没有保留模型额，你可以参考流程自己训练一个。

**Comment by taishan1994** [comment]
> 您好，请问可以给args.json吗？以及网盘中的模型文件是CHIP2020的模型吗？

之前是没有保存args.json，后面改了才有的，你可以参考训练的参数自己生成一个。
