### ISSUE TITLE
main.py运行问题

### ISSUE THREAD

**Issue by EpichubS** [taishan1994/pytorch_bert_bilstm_crf_ner#27]
作者您好！我是小白，运行main.py出错，维度有问题！想询问一下解决方法。
![image](https://user-images.githubusercontent.com/53176835/203822445-38515d00-52ea-4a48-9591-50fc5b73abf9.png)

**Comment by taishan1994** [comment]
> 作者您好！我是小白，运行main.py出错，维度有问题！想询问一下解决方法。 ![image](https://user-images.githubusercontent.com/53176835/203822445-38515d00-52ea-4a48-9591-50fc5b73abf9.png)

使用得什么数据集，怎么运行的。

**Comment by EpichubS** [comment]
使用的cner中final_data，直接在pycharm中运行的。参数调用的config.py的默认参数（已按自己路径做了更改）。

**Comment by taishan1994** [comment]
> 使用的cner中final_data，直接在pycharm中运行的。参数调用的config.py的默认参数（已按自己路径做了更改）。

最好在命令行使用指令运行。

**Comment by EpichubS** [comment]
![image](https://user-images.githubusercontent.com/53176835/203828014-92734650-b69a-4c56-868e-ad10b0b2bfe4.png)

**Comment by EpichubS** [comment]
线性层输出为4800x33，下一行中batch_size=32，seq_len=256

**Comment by taishan1994** [comment]
> 线性层输出为4800x33，下一行中batch_size=32，seq_len=256

最大长度应该是150.

**Comment by EpichubS** [comment]
好的，感谢作者！

**Comment by EpichubS** [comment]
您好！我还想问一下，这个seq_len由什么确定的呢？ 感谢！

**Comment by taishan1994** [comment]
> 您好！我还想问一下，这个seq_len由什么确定的呢？ 感谢！

自己根据数据的平均长度设置。
