### ISSUE TITLE
作者您好，在运行main.py时，总是提醒KeyError，可以请教一下这是怎么回事吗？

### ISSUE THREAD

**Issue by jyc0316** [taishan1994/pytorch_bert_bilstm_crf_ner#28]
[我尝试把这几个参数改了形式也不行]
![1670164304372](https://user-images.githubusercontent.com/71545733/205496672-e4f748a9-2105-4508-84f0-e38caae7c756.png)

**Comment by taishan1994** [comment]
> [我尝试把这几个参数改了形式也不行] ![1670164304372](https://user-images.githubusercontent.com/71545733/205496672-e4f748a9-2105-4508-84f0-e38caae7c756.png)

命令行参数里面的单引号全部换成双引号。
