### ISSUE TITLE
请问labels.txt中对应的类别都是什么？

### ISSUE THREAD

**Issue by MgArcher** [taishan1994/pytorch_bert_bilstm_crf_ner#3]

**Comment by taishan1994** [comment]
name 姓名 
conf 国籍 
race 民族
pro 专业
edu 教育
title 职称
org 职位
loc 籍贯

**Comment by taishan1994** [comment]
> _No description provided._

name 姓名
conf 国籍
race 民族
pro 专业
edu 教育
title 职称
org 职位
loc 籍贯
