### ISSUE TITLE
作者您好，请教一下为什么main.py中test方法用的是训练集

### ISSUE THREAD

**Issue by lucashu1234** [taishan1994/pytorch_bert_bilstm_crf_ner#30]
请教一下为什么main.py中测试结果用的是训练集

**Comment by taishan1994** [comment]
> 请教一下为什么main.py中测试结果用的是训练集

具体是哪个地方呢？

**Comment by lucashu1234** [comment]
main.py的109行test方法中 测试的时候传的数据用的是dev_loader，为什么不是test_loader,test_loader数据好像一直都没用到

**Comment by taishan1994** [comment]
> main.py的109行test方法中 测试的时候传的数据用的是dev_loader，为什么不是test_loader,test_loader数据好像一直都没用到

因为有的数据只有dev数据，没有test数据，这里统一都设置成了dev，你可以根据实际情况进行修改。

**Comment by taishan1994** [comment]
> main.py的109行test方法中 测试的时候传的数据用的是dev_loader，为什么不是test_loader,test_loader数据好像一直都没用到

现在改了下，如果有test_loader就使用test_loader，否则传参时设置test_loader为dev_loader即可。

**Comment by lucashu1234** [comment]
还补充个问题，89行 batch_output_all = np.append(batch_output_all, batch_output, axis=0) 
这个方法在numpy最新的numpy版本上会出现拼接数组的时候个数不对齐的问题，这里不能用最新的numpy版本

**Comment by lucashu1234** [comment]
test方法还是有点问题，该方法数据用的test_loader，113行验证的标签用的测试集的标签dev_callback_info

**Comment by lucashu1234** [comment]
89行numpy不兼容的原因找到了， batch_output_all = np.append(batch_output_all, batch_output, axis=0)
batch_output本来是个二维数组，当某个batch中batch_output只有一条数据时，会把自动当成一维数组处理，造成维度不一致的报错

**Comment by taishan1994** [comment]
> test方法还是有点问题，该方法数据用的test_loader，113行验证的标签用的测试集的标签dev_callback_info

这个修改了下。

**Comment by taishan1994** [comment]
> 89行numpy不兼容的原因找到了， batch_output_all = np.append(batch_output_all, batch_output, axis=0) batch_output本来是个二维数组，当某个batch中batch_output只有一条数据时，会把自动当成一维数组处理，造成维度不一致的报错

这个也改了下。

**Comment by VICKY-ZZ** [comment]
> 签dev_callback_info
使得！我也发现了这个问题，请问最终解决了吗

**Comment by VICKY-ZZ** [comment]
> > 89行numpy不兼容的原因找到了， batch_output_all = np.append(batch_output_all, batch_output, axis=0) batch_output本来是个二维数组，当某个batch中batch_output只有一条数据时，会把自动当成一维数组处理，造成维度不一致的报错
> 
> 这个也改了下。

请问最终是如何解决的呐？感谢！
