### ISSUE TITLE
作者您好，想要运行观点抽取实例

### ISSUE THREAD

**Issue by xian-xian** [taishan1994/pytorch_bert_bilstm_crf_ner#31]
但是当我按照您的readme文件中的命令运行时，会出现错误找不到文件，想要问一下gdcq里面需要用到的final_data和mid_data，以及mid_data下面的noe_ent2id.json这些文件需要我们在什么地方去获取呢？
Traceback (most recent call last):
  File "main.py", line 533, in <module>
    ent2id_dict = commonUtils.read_json(other_path, 'nor_ent2id')
  File "/gemini/code/pytorch_bert_bilstm_crf_ner-main/utils/commonUtils.py", line 76, in read_json
    with open(os.path.join(data_dir, '{}.json'.format(desc)), 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './data/gdcq/mid_data/nor_ent2id.json'

**Comment by taishan1994** [comment]
> 但是当我按照您的readme文件中的命令运行时，会出现错误找不到文件，想要问一下gdcq里面需要用到的final_data和mid_data，以及mid_data下面的noe_ent2id.json这些文件需要我们在什么地方去获取呢？ Traceback (most recent call last): File "main.py", line 533, in ent2id_dict = commonUtils.read_json(other_path, 'nor_ent2id') File "/gemini/code/pytorch_bert_bilstm_crf_ner-main/utils/commonUtils.py", line 76, in read_json with open(os.path.join(data_dir, '{}.json'.format(desc)), 'r', encoding='utf-8') as f: FileNotFoundError: [Errno 2] No such file or directory: './data/gdcq/mid_data/nor_ent2id.json'

data/gdcq/下运行process.py得到mid_data下的数据，修改preprocess.py里面相关参数得到final_data下的数据。

**Comment by xian-xian** [comment]
>您好，可是还是会出现找不到文件的错误，大佬有什么办法吗？
Traceback (most recent call last):
  File "process.py", line 43, in <module>
    with open('../mid_data/labels.json', 'w', encoding="utf-8") as fp:
FileNotFoundError: [Errno 2] No such file or directory: '../mid_data/labels.json'


非常感谢您回答我的问题
