### ISSUE TITLE
大佬，您好，我想问下为什么main.py文件中，当use_crf == 'True'的时候，第89行的batch_output报错是list类型的呀？

### ISSUE THREAD

**Issue by fayfay2023** [taishan1994/pytorch_bert_bilstm_crf_ner#32]
![image](https://user-images.githubusercontent.com/124534819/216849979-dccfae1f-38f4-4602-9f71-afe6bd05f909.png)

**Comment by taishan1994** [comment]
> ![image](https://user-images.githubusercontent.com/124534819/216849979-dccfae1f-38f4-4602-9f71-afe6bd05f909.png)

有点问题，修改了下，你改下再试试看。

**Comment by fayfay2023** [comment]
感谢~这个没问题了，但92行拼接的时候还是出现的维度错误

**Comment by fayfay2023** [comment]
![image](https://user-images.githubusercontent.com/124534819/216893299-513814fa-0e17-404a-bdc0-a4ef0ee03ea2.png)

**Comment by taishan1994** [comment]
> ![image](https://user-images.githubusercontent.com/124534819/216893299-513814fa-0e17-404a-bdc0-a4ef0ee03ea2.png)

再修改了下，看看能不能行，不行再打印下batch_output的形状看看是什么。

**Comment by fayfay2023** [comment]
这里显示batch_out.shape是(1,15)，请问应该如何处理成32维呢？
![image](https://user-images.githubusercontent.com/124534819/216897320-ef7dbaaf-dac2-4dff-b874-a992d847bca2.png)

**Comment by taishan1994** [comment]
> 这里显示batch_out.shape是(1,15)，请问应该如何处理成32维呢？ ![image](https://user-images.githubusercontent.com/124534819/216897320-ef7dbaaf-dac2-4dff-b874-a992d847bca2.png)

发现之前改错了，你再看看代码更新下。
