### ISSUE TITLE
运行main.py时

### ISSUE THREAD

**Issue by xian-xian** [taishan1994/pytorch_bert_bilstm_crf_ner#33]
Namespace(adam_epsilon=1e-08, bert_dir='../model_hub/chinese-bert-wwm-ext/', crf_lr=0.03, data_dir='./data/gdcq', data_name='gdcq', dropout=0.3, dropout_prob=0.3, eval_batch_size=64, gpu_ids='0', log_dir='./logs/', lr=3e-05, lstm_hidden=128, max_grad_norm=1.0, max_seq_len=70, model_name='chinese-bert-wwm-ext_crf', num_layers=1, num_tags=65, other_lr=0.0003, output_dir='./checkpoints/', seed=123, swa_start=3, train_batch_size=64, train_epochs=10, use_crf='True', use_idcnn='False', use_kd='False', use_lstm='False', use_tensorboard='True', warmup_proportion=0.1, weight_decay=0.01)
Traceback (most recent call last):
  File "main.py", line 569, in <module>
    bertForNer = BertForNer(args, train_loader, dev_loader, dev_loader, id2query)
  File "main.py", line 32, in __init__
    model = bert_ner_model.BertNerModel(args)
  File "/gemini/code/pytorch_bert_bilstm_crf_ner-main/bert_ner_model.py", line 200, in __init__
    super(BertNerModel, self).__init__(bert_dir=args.bert_dir, dropout_prob=args.dropout_prob, model_name=args.model_name)
  File "/gemini/code/pytorch_bert_bilstm_crf_ner-main/bert_base_model.py", line 11, in __init__
    assert os.path.exists(bert_dir) and os.path.exists(config_path), \
AssertionError: pretrained bert file does not exist
作者您好，执行命令时出现这个问题是怎么回事呢？可以帮忙解答一下吗？

**Comment by taishan1994** [comment]
> Namespace(adam_epsilon=1e-08, bert_dir='../model_hub/chinese-bert-wwm-ext/', crf_lr=0.03, data_dir='./data/gdcq', data_name='gdcq', dropout=0.3, dropout_prob=0.3, eval_batch_size=64, gpu_ids='0', log_dir='./logs/', lr=3e-05, lstm_hidden=128, max_grad_norm=1.0, max_seq_len=70, model_name='chinese-bert-wwm-ext_crf', num_layers=1, num_tags=65, other_lr=0.0003, output_dir='./checkpoints/', seed=123, swa_start=3, train_batch_size=64, train_epochs=10, use_crf='True', use_idcnn='False', use_kd='False', use_lstm='False', use_tensorboard='True', warmup_proportion=0.1, weight_decay=0.01) Traceback (most recent call last): File "main.py", line 569, in bertForNer = BertForNer(args, train_loader, dev_loader, dev_loader, id2query) File "main.py", line 32, in **init** model = bert_ner_model.BertNerModel(args) File "/gemini/code/pytorch_bert_bilstm_crf_ner-main/bert_ner_model.py", line 200, in **init** super(BertNerModel, self).**init**(bert_dir=args.bert_dir, dropout_prob=args.dropout_prob, model_name=args.model_name) File "/gemini/code/pytorch_bert_bilstm_crf_ner-main/bert_base_model.py", line 11, in **init** assert os.path.exists(bert_dir) and os.path.exists(config_path), AssertionError: pretrained bert file does not exist 作者您好，执行命令时出现这个问题是怎么回事呢？可以帮忙解答一下吗？

 ——project
 ————model_hub
 ——————chinese-bert-wwm-ext
 ————————vocab.txt
 ————————pytorch_model.bin
 ————————config.json
 ——————其它模型路径
 ————pytorch_bert_bilstm_crf_ner

在pytorch_bert_bilstm_crf_ner的同级目录新建model_hub/chinese-bert-wwm-ext/，去https://huggingface.co/hfl/chinese-bert-wwm-ext/tree/main下载相关文件放置进去。

**Comment by xian-xian** [comment]
> 



> > 命名空间（adam_epsilon=1e-08， bert_dir='../model_hub/Chinese-bert-wwm-ext/'， crf_lr=0.03， data_dir='./data/gdcq'， data_name='GDCQ'， dropout=0.3， dropout_prob=0.3， eval_batch_size=64， gpu_ids='0'， log_dir='./logs/'， lr=3e-05， lstm_hidden=128， max_grad_norm=1.0， max_seq_len=70， model_name='Chinese-bert-WWM-ext_crf'， num_layers=1， num_tags=65， other_lr=0.0003， output_dir='./检查点/'， 种子=123， swa_start=3， train_batch_size=64， train_epochs=10， use_crf='真'， use_idcnn='假'， use_kd='假'， use_lstm='假'， use_tensorboard='真'， warmup_proportion=0.1， weight_decay=0.01） 回溯（最近一次调用）： 文件 “main.py”，第 569 行，在 bertForNer = BertForNer（args， train_loader， dev_loader， dev_loader， id2query） 文件 “main.py”，第 32 行， 在**初始化**模型中 = bert_ner_model。BertNerModel（args） File “/gemini/code/pytorch_bert_bilstm_crf_ner-main/bert_ner_model.py”， line 200， in **init** super（BertNerModel， self）.**init**（bert_dir=args.bert_dir， dropout_prob=args.dropout_prob， model_name=args.model_name） 文件 “/gemini/code/pytorch_bert_bilstm_crf_ner-main/bert_base_model.py”， 第 11 行， 在 **init** assert os.path.exists（bert_dir） 和 os.path.exists（config_path）， AssertionError： pretrain bert file not exists 作者您好，执行命令时出现这个问题是怎么回事呢？可以帮忙解答一下吗？
> 
> ——项目————model_hub ——————中文-伯特-WWM-ext ————————词汇.txt ————————pytorch_model.bin ————————config.json ——————其它模型路径 ————pytorch_bert_bilstm_crf_ner
> 
> 在pytorch_bert_bilstm_crf_ner的同级目录新建model_hub/Chinese-bert-wwm-ext/，去 https://huggingface.co/hfl/chinese-bert-wwm-ext/tree/main 下载相关文件放置进去。

您好，我已经创建了model_hub,并且下载了Chinese-bert-wwm-ext放在里面，但是还是会有这个报错，怎么办呢？

**Comment by taishan1994** [comment]
> > 
> 
> > > 命名空间（adam_epsilon=1e-08， bert_dir='../model_hub/Chinese-bert-wwm-ext/'， crf_lr=0.03， data_dir='./data/gdcq'， data_name='GDCQ'， dropout=0.3， dropout_prob=0.3， eval_batch_size=64， gpu_ids='0'， log_dir='./logs/'， lr=3e-05， lstm_hidden=128， max_grad_norm=1.0， max_seq_len=70， model_name='Chinese-bert-WWM-ext_crf'， num_layers=1， num_tags=65， other_lr=0.0003， output_dir='./检查点/'， 种子=123， swa_start=3， train_batch_size=64， train_epochs=10， use_crf='真'， use_idcnn='假'， use_kd='假'， use_lstm='假'， use_tensorboard='真'， warmup_proportion=0.1， weight_decay=0.01） 回溯（最近一次调用）： 文件 “main.py”，第 569 行，在 bertForNer = BertForNer（args， train_loader， dev_loader， dev_loader， id2query） 文件 “main.py”，第 32 行， 在**初始化**模型中 = bert_ner_model。BertNerModel（args） File “/gemini/code/pytorch_bert_bilstm_crf_ner-main/bert_ner_model.py”， line 200， in **init** super（BertNerModel， self）.**init**（bert_dir=args.bert_dir， dropout_prob=args.dropout_prob， model_name=args.model_name） 文件 “/gemini/code/pytorch_bert_bilstm_crf_ner-main/bert_base_model.py”， 第 11 行， 在 **init** assert os.path.exists（bert_dir） 和 os.path.exists（config_path）， AssertionError： pretrain bert file not exists 作者您好，执行命令时出现这个问题是怎么回事呢？可以帮忙解答一下吗？
> > 
> > 
> > ——项目————model_hub ——————中文-伯特-WWM-ext ————————词汇.txt ————————pytorch_model.bin ————————config.json ——————其它模型路径 ————pytorch_bert_bilstm_crf_ner
> > 在pytorch_bert_bilstm_crf_ner的同级目录新建model_hub/Chinese-bert-wwm-ext/，去 https://huggingface.co/hfl/chinese-bert-wwm-ext/tree/main 下载相关文件放置进去。
> 
> 您好，我已经创建了model_hub,并且下载了Chinese-bert-wwm-ext放在里面，但是还是会有这个报错，怎么办呢？

所有名称和路径最好都使用小写。

**Comment by xian-xian** [comment]
> > > 
> > 
> > 
> > > > 命名空间（adam_epsilon=1e-08， bert_dir='../model_hub/Chinese-bert-wwm-ext/'， crf_lr=0.03， data_dir='./data/gdcq'， data_name='GDCQ'， dropout=0.3， dropout_prob=0.3， eval_batch_size=64， gpu_ids='0'， log_dir='./logs/'， lr=3e-05， lstm_hidden=128， max_grad_norm=1.0， max_seq_len=70， model_name='Chinese-bert-WWM-ext_crf'， num_layers=1， num_tags=65， other_lr=0.0003， output_dir='./检查点/'， 种子=123， swa_start=3， train_batch_size=64， train_epochs=10， use_crf='真'， use_idcnn='假'， use_kd='假'， use_lstm='假'， use_tensorboard='真'， warmup_proportion=0.1， weight_decay=0.01） 回溯（最近一次调用）： 文件 “main.py”，第 569 行，在 bertForNer = BertForNer（args， train_loader， dev_loader， dev_loader， id2query） 文件 “main.py”，第 32 行， 在**初始化**模型中 = bert_ner_model。BertNerModel（args） File “/gemini/code/pytorch_bert_bilstm_crf_ner-main/bert_ner_model.py”， line 200， in **init** super（BertNerModel， self）.**init**（bert_dir=args.bert_dir， dropout_prob=args.dropout_prob， model_name=args.model_name） 文件 “/gemini/code/pytorch_bert_bilstm_crf_ner-main/bert_base_model.py”， 第 11 行， 在 **init** assert os.path.exists（bert_dir） 和 os.path.exists（config_path）， AssertionError： pretrain bert file not exists 作者您好，执行命令时出现这个问题是怎么回事呢？可以帮忙解答一下吗？
> > > 
> > > 
> > > ——项目————model_hub ——————中文-伯特-WWM-ext ————————词汇.txt ————————pytorch_model.bin ————————config.json ——————其它模型路径 ————pytorch_bert_bilstm_crf_ner
> > > 在pytorch_bert_bilstm_crf_ner的同级目录新建model_hub/Chinese-bert-wwm-ext/，去 https://huggingface.co/hfl/chinese-bert-wwm-ext/tree/main 下载相关文件放置进去。
> > 
> > 
> > 您好，我已经创建了model_hub,并且下载了Chinese-bert-wwm-ext放在里面，但是还是会有这个报错，怎么办呢？
> 
> 所有名称和路径最好都使用小写。
作者您好，确实都是使用的小写字母，还是会报错，研一小白求求作者大大帮帮忙

**Comment by taishan1994** [comment]
> bert_dir='../model_hub/Chinese-bert-wwm-ext/'

你这里bert_dir='../model_hub/Chinese-bert-wwm-ext/'不是有大写么？运行时最好是在命令行带参数运行，不要直接在pycharm里面运行main.py。

**Comment by taishan1994** [comment]
> > > > 
> > > 
> > > 
> > > > > 命名空间（adam_epsilon=1e-08， bert_dir='../model_hub/Chinese-bert-wwm-ext/'， crf_lr=0.03， data_dir='./data/gdcq'， data_name='GDCQ'， dropout=0.3， dropout_prob=0.3， eval_batch_size=64， gpu_ids='0'， log_dir='./logs/'， lr=3e-05， lstm_hidden=128， max_grad_norm=1.0， max_seq_len=70， model_name='Chinese-bert-WWM-ext_crf'， num_layers=1， num_tags=65， other_lr=0.0003， output_dir='./检查点/'， 种子=123， swa_start=3， train_batch_size=64， train_epochs=10， use_crf='真'， use_idcnn='假'， use_kd='假'， use_lstm='假'， use_tensorboard='真'， warmup_proportion=0.1， weight_decay=0.01） 回溯（最近一次调用）： 文件 “main.py”，第 569 行，在 bertForNer = BertForNer（args， train_loader， dev_loader， dev_loader， id2query） 文件 “main.py”，第 32 行， 在**初始化**模型中 = bert_ner_model。BertNerModel（args） File “/gemini/code/pytorch_bert_bilstm_crf_ner-main/bert_ner_model.py”， line 200， in **init** super（BertNerModel， self）.**init**（bert_dir=args.bert_dir， dropout_prob=args.dropout_prob， model_name=args.model_name） 文件 “/gemini/code/pytorch_bert_bilstm_crf_ner-main/bert_base_model.py”， 第 11 行， 在 **init** assert os.path.exists（bert_dir） 和 os.path.exists（config_path）， AssertionError： pretrain bert file not exists 作者您好，执行命令时出现这个问题是怎么回事呢？可以帮忙解答一下吗？
> > > > 
> > > > 
> > > > ——项目————model_hub ——————中文-伯特-WWM-ext ————————词汇.txt ————————pytorch_model.bin ————————config.json ——————其它模型路径 ————pytorch_bert_bilstm_crf_ner
> > > > 在pytorch_bert_bilstm_crf_ner的同级目录新建model_hub/Chinese-bert-wwm-ext/，去 https://huggingface.co/hfl/chinese-bert-wwm-ext/tree/main 下载相关文件放置进去。
> > > 
> > > 
> > > 您好，我已经创建了model_hub,并且下载了Chinese-bert-wwm-ext放在里面，但是还是会有这个报错，怎么办呢？
> > 
> > 
> > 所有名称和路径最好都使用小写。
> > 作者您好，确实都是使用的小写字母，还是会报错，研一小白求求作者大大帮帮忙

你这里bert_dir='../model_hub/Chinese-bert-wwm-ext/'不是有大写么？运行时最好是在命令行带参数运行，不要直接在pycharm里面运行main.py。

**Comment by xian-xian** [comment]
> > bert_dir='../model_hub/Chinese-bert-wwm-ext/'
> 
> 你这里bert_dir='../model_hub/Chinese-bert-wwm-ext/'不是有大写么？运行时最好是在命令行带参数运行，不要直接在pycharm里面运行 main.py。

我检查了我运行的代码，时直接复制的readme里面的python main.py+参数命令，不知道为什么复制过来大写了，我是在服务器的终端运行的

**Comment by xian-xian** [comment]
> > > > > 
> > > > 
> > > > 
> > > > > > 命名空间（adam_epsilon=1e-08， bert_dir='../model_hub/Chinese-bert-wwm-ext/'， crf_lr=0.03， data_dir='./data/gdcq'， data_name='GDCQ'， dropout=0.3， dropout_prob=0.3， eval_batch_size=64， gpu_ids='0'， log_dir='./logs/'， lr=3e-05， lstm_hidden=128， max_grad_norm=1.0， max_seq_len=70， model_name='Chinese-bert-WWM-ext_crf'， num_layers=1， num_tags=65， other_lr=0.0003， output_dir='./检查点/'， 种子=123， swa_start=3， train_batch_size=64， train_epochs=10， use_crf='真'，use_idcnn='假'， use_kd='假'， use_lstm='假'， use_tensorboard='真'， warmup_proportion=0.1， weight_decay=0.01） 回溯（最近一次调用）： 文件 “main.py”，第 569 行，在 bertForNer = BertForNer（args， train_loader， dev_loader， dev_loader， id2query） 文件 “main.py”，第 32 行， 在**初始化**模型中 = bert_ner_model。BertNerModel（args） File “/gemini/code/pytorch_bert_bilstm_crf_ner-main/bert_ner_model.py”， line 200， in **init** super（BertNerModel， self）.**init**（bert_dir=args.bert_dir， dropout_prob=args.dropout_prob， model_name=args.model_name） 文件 “/gemini/code/pytorch_bert_bilstm_crf_ner-main/bert_base_model.py”， 第 11 行， 在 **init** assert os.path.exists（bert_dir） 和 os.path.exists（config_path）， AssertionError： pretrain bert file not exists 作者您好，执行命令时出现这个问题是怎么回事呢？可以帮忙解答一下吗？
> > > > > 
> > > > > 
> > > > > ——项目————model_hub ——————中文-伯特-WWM-ext ————————词汇.txt ————————pytorch_model.bin ————————config.json ——————其它模型路径 ————pytorch_bert_bilstm_crf_ner
> > > > > 在pytorch_bert_bilstm_crf_ner的同级目录新建model_hub/Chinese-bert-wwm-ext/，去 https://huggingface.co/hfl/chinese-bert-wwm-ext/tree/main 下载相关文件放置进去。
> > > > 
> > > > 
> > > > 您好，我已经创建了model_hub，并且下载了Chinese-bert-wwm-ext放在里面，但是还是会有这个报错，怎么办呢？
> > > 
> > > 
> > > 所有名称和路径最好都使用小写。
> > > 作者您好，确实都是使用的小写字母，还是会报错，研一小白求求作者大大帮帮忙
> 
> 你这里bert_dir='../model_hub/Chinese-bert-wwm-ext/'不是有大写么？运行时最好是在命令行带参数运行，不要直接在pycharm里面运行 main.py。

![微信0821](https://user-images.githubusercontent.com/57379949/216896236-25072f48-40fd-48cc-96c3-b00784898b60.png)
您好这是我的目录以及执行命令

**Comment by taishan1994** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > > > 命名空间（adam_epsilon=1e-08， bert_dir='../model_hub/Chinese-bert-wwm-ext/'， crf_lr=0.03， data_dir='./data/gdcq'， data_name='GDCQ'， dropout=0.3， dropout_prob=0.3， eval_batch_size=64， gpu_ids='0'， log_dir='./logs/'， lr=3e-05， lstm_hidden=128， max_grad_norm=1.0， max_seq_len=70， model_name='Chinese-bert-WWM-ext_crf'， num_layers=1， num_tags=65， other_lr=0.0003， output_dir='./检查点/'， 种子=123， swa_start=3， train_batch_size=64， train_epochs=10， use_crf='真'，use_idcnn='假'， use_kd='假'， use_lstm='假'， use_tensorboard='真'， warmup_proportion=0.1， weight_decay=0.01） 回溯（最近一次调用）： 文件 “main.py”，第 569 行，在 bertForNer = BertForNer（args， train_loader， dev_loader， dev_loader， id2query） 文件 “main.py”，第 32 行， 在**初始化**模型中 = bert_ner_model。BertNerModel（args） File “/gemini/code/pytorch_bert_bilstm_crf_ner-main/bert_ner_model.py”， line 200， in **init** super（BertNerModel， self）.**init**（bert_dir=args.bert_dir， dropout_prob=args.dropout_prob， model_name=args.model_name） 文件 “/gemini/code/pytorch_bert_bilstm_crf_ner-main/bert_base_model.py”， 第 11 行， 在 **init** assert os.path.exists（bert_dir） 和 os.path.exists（config_path）， AssertionError： pretrain bert file not exists 作者您好，执行命令时出现这个问题是怎么回事呢？可以帮忙解答一下吗？
> > > > > > 
> > > > > > 
> > > > > > ——项目————model_hub ——————中文-伯特-WWM-ext ————————词汇.txt ————————pytorch_model.bin ————————config.json ——————其它模型路径 ————pytorch_bert_bilstm_crf_ner
> > > > > > 在pytorch_bert_bilstm_crf_ner的同级目录新建model_hub/Chinese-bert-wwm-ext/，去 https://huggingface.co/hfl/chinese-bert-wwm-ext/tree/main 下载相关文件放置进去。
> > > > > 
> > > > > 
> > > > > 您好，我已经创建了model_hub，并且下载了Chinese-bert-wwm-ext放在里面，但是还是会有这个报错，怎么办呢？
> > > > 
> > > > 
> > > > 所有名称和路径最好都使用小写。
> > > > 作者您好，确实都是使用的小写字母，还是会报错，研一小白求求作者大大帮帮忙
> > 
> > 
> > 你这里bert_dir='../model_hub/Chinese-bert-wwm-ext/'不是有大写么？运行时最好是在命令行带参数运行，不要直接在pycharm里面运行 main.py。
> 
> ![微信0821](https://user-images.githubusercontent.com/57379949/216896236-25072f48-40fd-48cc-96c3-b00784898b60.png) 您好这是我的目录以及执行命令

你按照这种目录组织下：
——project
————model_hub
——————chinese-bert-wwm-ext
————————vocab.txt
————————pytorch_model.bin
————————config.json
——————其它模型路径
————pytorch_bert_bilstm_crf_ner
然后检查下大小写，应该就没什么问题了。

**Comment by xian-xian** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > > > 命名空间（adam_epsilon=1e-08， bert_dir='../model_hub/Chinese-bert-wwm-ext/'， crf_lr=0.03， data_dir='./data/gdcq'， data_name='GDCQ'， dropout=0.3， dropout_prob=0.3， eval_batch_size=64， gpu_ids='0'， log_dir='./logs/'， lr=3e-05， lstm_hidden=128， max_grad_norm=1.0， max_seq_len=70， model_name='Chinese-bert-WWM-ext_crf'， num_layers=1， num_tags=65， other_lr=0.0003， output_dir='./检查点/'， 种子=123， swa_start=3， train_batch_size=64， train_epochs=10， use_crf='真'，use_idcnn='假'， use_kd='假'， use_lstm='假'， use_tensorboard='真'， warmup_proportion=0.1， weight_decay=0.01） 回溯（最近一次调用）： 文件 “main.py”，第 569 行，在 bertForNer = BertForNer（args， train_loader， dev_loader， dev_loader， id2query） 文件 “main.py”，第 32 行， 在**初始化**模型中 = bert_ner_model。BertNerModel（args） File “/gemini/code/pytorch_bert_bilstm_crf_ner-main/bert_ner_model.py”， line 200， in **init** super（BertNerModel， self）.**init**（bert_dir=args.bert_dir， dropout_prob=args.dropout_prob， model_name=args.model_name） 文件 “/gemini/code/pytorch_bert_bilstm_crf_ner-main/bert_base_model.py”， 第 11 行， 在 **init** assert os.path.exists（bert_dir） 和 os.path.exists（config_path）， AssertionError： pretrain bert file not exists 作者您好，执行命令时出现这个问题是怎么回事呢？可以帮忙解答一下吗？
> > > > > > > 
> > > > > > > 
> > > > > > > ——项目————model_hub ——————中文-伯特-WWM-ext ————————词汇.txt ————————pytorch_model.bin ————————config.json ——————其它模型路径 ————pytorch_bert_bilstm_crf_ner
> > > > > > > 在pytorch_bert_bilstm_crf_ner的同级目录新建model_hub/Chinese-bert-wwm-ext/，去 https://huggingface.co/hfl/chinese-bert-wwm-ext/tree/main 下载相关文件放置进去。
> > > > > > 
> > > > > > 
> > > > > > 您好，我已经创建了model_hub，并且下载了Chinese-bert-wwm-ext放在里面，但是还是会有这个报错，怎么办呢？
> > > > > 
> > > > > 
> > > > > 所有名称和路径最好都使用小写。
> > > > > 作者您好，确实都是使用的小写字母，还是会报错，研一小白求求作者大大帮帮忙
> > > 
> > > 
> > > 你这里bert_dir='../model_hub/Chinese-bert-wwm-ext/'不是有大写么？运行时最好是在命令行带参数运行，不要直接在pycharm里面运行 main.py。
> > 
> > 
> > ![微信0821](https://user-images.githubusercontent.com/57379949/216896236-25072f48-40fd-48cc-96c3-b00784898b60.png) 您好这是我的目录以及执行命令
> 
> 你按照这种目录组织下： ——project ————model_hub ——————chinese-bert-wwm-ext ————————vocab.txt ————————pytorch_model.bin ————————config.json ——————其它模型路径 ————pytorch_bert_bilstm_crf_ner 然后检查下大小写，应该就没什么问题了。

还是报错了，同样的报错，呜呜呜

**Comment by taishan1994** [comment]
> > > > > > > > 
> > > > > > > 
> > > > > > > 
> > > > > > > > > 命名空间（adam_epsilon=1e-08， bert_dir='../model_hub/Chinese-bert-wwm-ext/'， crf_lr=0.03， data_dir='./data/gdcq'， data_name='GDCQ'， dropout=0.3， dropout_prob=0.3， eval_batch_size=64， gpu_ids='0'， log_dir='./logs/'， lr=3e-05， lstm_hidden=128， max_grad_norm=1.0， max_seq_len=70， model_name='Chinese-bert-WWM-ext_crf'， num_layers=1， num_tags=65， other_lr=0.0003， output_dir='./检查点/'， 种子=123， swa_start=3， train_batch_size=64， train_epochs=10， use_crf='真'，use_idcnn='假'， use_kd='假'， use_lstm='假'， use_tensorboard='真'， warmup_proportion=0.1， weight_decay=0.01） 回溯（最近一次调用）： 文件 “main.py”，第 569 行，在 bertForNer = BertForNer（args， train_loader， dev_loader， dev_loader， id2query） 文件 “main.py”，第 32 行， 在**初始化**模型中 = bert_ner_model。BertNerModel（args） File “/gemini/code/pytorch_bert_bilstm_crf_ner-main/bert_ner_model.py”， line 200， in **init** super（BertNerModel， self）.**init**（bert_dir=args.bert_dir， dropout_prob=args.dropout_prob， model_name=args.model_name） 文件 “/gemini/code/pytorch_bert_bilstm_crf_ner-main/bert_base_model.py”， 第 11 行， 在 **init** assert os.path.exists（bert_dir） 和 os.path.exists（config_path）， AssertionError： pretrain bert file not exists 作者您好，执行命令时出现这个问题是怎么回事呢？可以帮忙解答一下吗？
> > > > > > > > 
> > > > > > > > 
> > > > > > > > ——项目————model_hub ——————中文-伯特-WWM-ext ————————词汇.txt ————————pytorch_model.bin ————————config.json ——————其它模型路径 ————pytorch_bert_bilstm_crf_ner
> > > > > > > > 在pytorch_bert_bilstm_crf_ner的同级目录新建model_hub/Chinese-bert-wwm-ext/，去 https://huggingface.co/hfl/chinese-bert-wwm-ext/tree/main 下载相关文件放置进去。
> > > > > > > 
> > > > > > > 
> > > > > > > 您好，我已经创建了model_hub，并且下载了Chinese-bert-wwm-ext放在里面，但是还是会有这个报错，怎么办呢？
> > > > > > 
> > > > > > 
> > > > > > 所有名称和路径最好都使用小写。
> > > > > > 作者您好，确实都是使用的小写字母，还是会报错，研一小白求求作者大大帮帮忙
> > > > 
> > > > 
> > > > 你这里bert_dir='../model_hub/Chinese-bert-wwm-ext/'不是有大写么？运行时最好是在命令行带参数运行，不要直接在pycharm里面运行 main.py。
> > > 
> > > 
> > > ![微信0821](https://user-images.githubusercontent.com/57379949/216896236-25072f48-40fd-48cc-96c3-b00784898b60.png) 您好这是我的目录以及执行命令
> > 
> > 
> > 你按照这种目录组织下： ——project ————model_hub ——————chinese-bert-wwm-ext ————————vocab.txt ————————pytorch_model.bin ————————config.json ——————其它模型路径 ————pytorch_bert_bilstm_crf_ner 然后检查下大小写，应该就没什么问题了。
> 
> 还是报错了，同样的报错，呜呜呜

加我微信：15926459981
