### ISSUE TITLE
关于代码数据结果低于一般论文的结果

### ISSUE THREAD

**Issue by lucashu1234** [taishan1994/pytorch_bert_bilstm_crf_ner#34]
作者，您好：
          用本项目代码测试了CCKS2017  CCKS2019 WEIBO msra 等数据集，发现本项目的代码测试结果低于有些论文的测试结果，特别是召回率明显偏低，比如CCKS2017部分论文用BERT能达到百分之九十多，但是用本项目只有七十多，是数据集划分的不合理的原因吗

**Comment by taishan1994** [comment]
> 作者，您好： 用本项目代码测试了CCKS2017 CCKS2019 WEIBO msra 等数据集，发现本项目的代码测试结果低于有些论文的测试结果，特别是召回率明显偏低，比如CCKS2017部分论文用BERT能达到百分之九十多，但是用本项目只有七十多，是数据集划分的不合理的原因吗

比论文的效果低很正常，由很多因素造成，比如各种超参数，数据的处理和评价指标的计算，如果是要得到论文中的效果，最好还是找论文的源代码试试，这里的仅供学习用额。

**Comment by lucashu1234** [comment]
了解了，感谢作者的耐心解答
