### ISSUE TITLE
大哥你好。我想问一下File "/home/vrlab/wwt/pytorch_bert_bilstm_crf_ner-main/bert_base_model.py", line 11, in __init__     assert os.path.exists(bert_dir) and os.path.exists(config_path), \ AssertionError: pretrained bert file does not exist是为啥

### ISSUE THREAD

**Issue by tt199872** [taishan1994/pytorch_bert_bilstm_crf_ner#37]
File "/home/vrlab/wwt/pytorch_bert_bilstm_crf_ner-main/bert_base_model.py", line 11, in __init__
    assert os.path.exists(bert_dir) and os.path.exists(config_path), \
AssertionError: pretrained bert file does not exist

**Comment by taishan1994** [comment]
> File "/home/vrlab/wwt/pytorch_bert_bilstm_crf_ner-main/bert_base_model.py", line 11, in **init** assert os.path.exists(bert_dir) and os.path.exists(config_path), AssertionError: pretrained bert file does not exist

```
--project
----model_hub
--------chinese-bert-wwm-ext
------------pytorch_model.bin
------------config.json
------------vocab.txt
----pytorch_bert_bilstm_crf
```
是否下载了model_hub里面的文件。

**Comment by tt199872** [comment]
下载了，一开始点击bert-base-chinese出现404，然后我去hugging-face这个网站下载了。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "taishan1994/pytorch_bert_bilstm_crf_ner"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月10日(星期五) 晚上6:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [taishan1994/pytorch_bert_bilstm_crf_ner] 大哥你好。我想问一下File "/home/vrlab/wwt/pytorch_bert_bilstm_crf_ner-main/bert_base_model.py", line 11, in __init__     assert os.path.exists(bert_dir) and os.path.exists(config_path), \ AssertionError: pretrained bert file does not exist是为啥 (Issue #37)





  
File "/home/vrlab/wwt/pytorch_bert_bilstm_crf_ner-main/bert_base_model.py", line 11, in init assert os.path.exists(bert_dir) and os.path.exists(config_path), AssertionError: pretrained bert file does not exist
  --project ----model_hub --------chinese-bert-wwm-ext ------------pytorch_model.bin ------------config.json ------------vocab.txt ----pytorch_bert_bilstm_crf  
是否下载了model_hub里面的文件。

**Comment by taishan1994** [comment]
> 下载了，一开始点击bert-base-chinese出现404，然后我去hugging-face这个网站下载了。

--bert_dir="../model_hub/chinese-bert-wwm-ext/"  如果是上述目录结构，则model_hub前面是../。还有要在命令行运行，不要直接在pycharm里面运行。

**Comment by tt199872** [comment]
大哥你好，我从昨晚试到现在，然后我不管怎么改--bert_dir="../model_hub/chinese-bert-wwm-ext/"这里的相对路径，绝对路径我也试过了，不管怎么试，我在服务器linux上运行bash main.sh，就是找不到文件路径。







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "taishan1994/pytorch_bert_bilstm_crf_ner"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月10日(星期五) 晚上6:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [taishan1994/pytorch_bert_bilstm_crf_ner] 大哥你好。我想问一下File "/home/vrlab/wwt/pytorch_bert_bilstm_crf_ner-main/bert_base_model.py", line 11, in __init__     assert os.path.exists(bert_dir) and os.path.exists(config_path), \ AssertionError: pretrained bert file does not exist是为啥 (Issue #37)





  
下载了，一开始点击bert-base-chinese出现404，然后我去hugging-face这个网站下载了。
  
--bert_dir="../model_hub/chinese-bert-wwm-ext/"  如果是上述目录结构，则model_hub前面是../。还有要在命令行运行，不要直接在pycharm里面运行。

**Comment by taishan1994** [comment]
> 大哥你好，我从昨晚试到现在，然后我不管怎么改--bert_dir="../model_hub/chinese-bert-wwm-ext/"这里的相对路径，绝对路径我也试过了，不管怎么试，我在服务器linux上运行bash main.sh，就是找不到文件路径。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "taishan1994/pytorch_bert_bilstm_crf_ner" ***@***.***&gt;; 发送时间:&nbsp;2023年3月10日(星期五) 晚上6:37 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [taishan1994/pytorch_bert_bilstm_crf_ner] 大哥你好。我想问一下File "/home/vrlab/wwt/pytorch_bert_bilstm_crf_ner-main/bert_base_model.py", line 11, in __init__ assert os.path.exists(bert_dir) and os.path.exists(config_path), \ AssertionError: pretrained bert file does not exist是为啥 (Issue #37) 下载了，一开始点击bert-base-chinese出现404，然后我去hugging-face这个网站下载了。
> --bert_dir="../model_hub/chinese-bert-wwm-ext/" 如果是上述目录结构，则model_hub前面是../。还有要在命令行运行，不要直接在pycharm里面运行。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

加我微信15926459981
