### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by chaos130** [taishan1994/pytorch_bert_bilstm_crf_ner#39]
ValueError: mask of the first timestep must all be on
我想请问一下这个是什么问题，谷歌上说是CRF层上有问题，掩码没有设置成1，可是我不知道怎么解决

**Comment by taishan1994** [comment]
> ValueError: mask of the first timestep must all be on 我想请问一下这个是什么问题，谷歌上说是CRF层上有问题，掩码没有设置成1，可是我不知道怎么解决

pytorch-crf版本要是0.7.2

**Comment by chaos130** [comment]
版本是0.7.2，问题还是没有解决

**Comment by taishan1994** [comment]
> 版本是0.7.2，问题还是没有解决

哪里报错了你打印一下那个变量看看是什么。

**Comment by chaos130** [comment]
我的tansformers = 4.5
pytorch-crf = 0.7.2
pytorch1.7.1+cuda11.0
错误raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '0.10.1,<0.11'

**Comment by taishan1994** [comment]
> 我的tansformers = 4.5 pytorch-crf = 0.7.2 pytorch1.7.1+cuda11.0 错误raise InvalidVersion(f"Invalid version: '{version}'") packaging.version.InvalidVersion: Invalid version: '0.10.1,<0.11'

```pip install packaging==21.3```

**Comment by chaos130** [comment]
实在不好意思
raise ValueError('mask of the first timestep must all be on')
ValueError: mask of the first timestep must all be on
我是个新手，错误又回来了

**Comment by chaos130** [comment]
我就是直接把你的项目git到服务器，然后修改了一下脚本路径。什么也没动

**Comment by taishan1994** [comment]
> 我就是直接把你的项目git到服务器，然后修改了一下脚本路径。什么也没动

加我微信：15926459981

**Comment by chaos130** [comment]
加了

**Comment by zdshang** [comment]
您好，我现在也出了这个问题，请问最后是怎么解决的呢
