### ISSUE TITLE
大佬您好，可以帮忙看看这个bug吗

### ISSUE THREAD

**Issue by yjj-ui** [taishan1994/pytorch_bert_bilstm_crf_ner#40]
网上搜了很多教程，都没有改成功，新手小白真的很崩溃，谢谢大佬了
<img width="741" alt="bug" src="https://user-images.githubusercontent.com/126142334/227271457-8799f099-00e2-4462-b9c4-88f313ae7e6b.PNG">

**Comment by yjj-ui** [comment]
应该是batch_output这行出的错，有翻到之前有人问过您类似的问题，但是按照您更新后的代码，仍然会出现这个问题
<img width="425" alt="bug" src="https://user-images.githubusercontent.com/126142334/227273740-6ca38541-8dc5-4317-b745-4356b1d1d27c.PNG">

**Comment by taishan1994** [comment]
> 网上搜了很多教程，都没有改成功，新手小白真的很崩溃，谢谢大佬了 <img alt="bug" width="741" src="https://user-images.githubusercontent.com/126142334/227271457-8799f099-00e2-4462-b9c4-88f313ae7e6b.PNG">

改了下代码，你再试试。

**Comment by yjj-ui** [comment]
又出现了这个问题
<img width="800" alt="bug" src="https://user-images.githubusercontent.com/126142334/227411085-33b66316-2029-4ade-8909-22140ceddcbf.PNG">

**Comment by taishan1994** [comment]
> 又出现了这个问题 <img alt="bug" width="800" src="https://user-images.githubusercontent.com/126142334/227411085-33b66316-2029-4ade-8909-22140ceddcbf.PNG">

打印一下batch_output是什么

**Comment by yjj-ui** [comment]
刚刚打印了一下，每条数据长度都是一样的
<img width="285" alt="bug" src="https://user-images.githubusercontent.com/126142334/227417562-9acb8c56-0db8-4753-9071-915d7625d73a.PNG">

**Comment by taishan1994** [comment]
> 刚刚打印了一下，每条数据长度都是一样的 <img alt="bug" width="285" src="https://user-images.githubusercontent.com/126142334/227417562-9acb8c56-0db8-4753-9071-915d7625d73a.PNG">

batch_output = np.array(batch_output)注释掉。然后最主要是看看最后一个batch_output是什么样的。

**Comment by yjj-ui** [comment]
> 

大佬我打印看了一下，发现最后一个batch_out里有一条长度不是128，为什么会出现这种情况呢，需要怎么处理数据呢
<img width="751" alt="bug" src="https://user-images.githubusercontent.com/126142334/227420455-a9652358-3e5b-44bf-9884-8eb13f297c3f.PNG">

**Comment by taishan1994** [comment]
> > 
> 
> 大佬我打印看了一下，发现最后一个batch_out里有一条长度不是128，为什么会出现这种情况呢，需要怎么处理数据呢 <img alt="bug" width="751" src="https://user-images.githubusercontent.com/126142334/227420455-a9652358-3e5b-44bf-9884-8eb13f297c3f.PNG">

transformers是4.5.0版本的么。

**Comment by yjj-ui** [comment]
> > > 
> > 
> > 
> > 大佬我打印看了一下，发现最后一个batch_out里有一条长度不是128，为什么会出现这种情况呢，需要怎么处理数据呢 <img alt="bug" width="751" src="https://user-images.githubusercontent.com/126142334/227420455-a9652358-3e5b-44bf-9884-8eb13f297c3f.PNG">
> 
> transformers是4.5.0版本的么。

一开始用的4.22.0，后来改成4.5.0还是这个问题，另外pytorch-crf也是0.7.2

**Comment by taishan1994** [comment]
> > transformers是4.5.0版本的么。
> 
> 一开始用的4.22.0，后来改成4.5.0还是这个问题，另外pytorch-crf也是0.7.2

把那条数据删了吧。

**Comment by yjj-ui** [comment]
嗯嗯数据处理掉能跑了，谢谢大佬太感谢了，另外刚刚调了一些其他各种版本，发现如果不处理数据的话，注释掉batch_output = np.array(batch_output)也可以跑了，这句在运行代码的时候，可以注释掉吗，是非必要的吗

**Comment by taishan1994** [comment]
> 嗯嗯数据处理掉能跑了，谢谢大佬太感谢了，另外刚刚调了一些其他各种版本，发现如果不处理数据的话，注释掉batch_output = np.array(batch_output)也可以跑了，这句在运行代码的时候，可以注释掉吗，是非必要的吗

这个必须注释掉了，删掉也行。

**Comment by yjj-ui** [comment]
谢谢大佬耐心解答！太感谢啦！
