### ISSUE TITLE
对BERT模型进行继续预训练对提高性能是否有帮助？

### ISSUE THREAD

**Issue by 943433536** [taishan1994/pytorch_bert_bilstm_crf_ner#43]
您好，我想对铁路领域的文本进行实体识别，由于铁路语料与通用语料差距较大，首先使用大量铁路领域无标注的文本对bert模型进行继续预训练。再将这个新得到的bert模型应用于bert-bilstm-crf模型中，是否会提高模型在铁路领域有标注的语料上的精度呢？

**Comment by taishan1994** [comment]
> 您好，我想对铁路领域的文本进行实体识别，由于铁路语料与通用语料差距较大，首先使用大量铁路领域无标注的文本对bert模型进行继续预训练。再将这个新得到的bert模型应用于bert-bilstm-crf模型中，是否会提高模型在铁路领域有标注的语料上的精度呢？

直觉上应该有效果的，不过要先确保继续预训练后的模型比之前的好，再迁移到这个任务上。

**Comment by 943433536** [comment]
1.我做了实验，在哈工大那个chinese-bert-wwm-ext基础上做了增量预训练，实验结果是在cner数据集上与原始bert相比F1下降了0.2，在我的铁路数据集上F1提高了0.7，实验还算成功，也算验证了Don't Stop Pretraining: Adapt Language Models to Domains and Tasks这篇文章的观点吧。
2.我还有一个问题，您这个模型，在做fine-tuning时，是固定bert模型内部参数，只调分类器参数，还是bert和分类器参数一起调呢？

**Comment by 943433536** [comment]
> > 您好，我想对铁路领域的文本进行实体识别，由于铁路语料与通用语料差距较大，首先使用大量铁路领域无标注的文本对bert模型进行继续预训练。再将这个新得到的bert模型应用于bert-bilstm-crf模型中，是否会提高模型在铁路领域有标注的语料上的精度呢？
> 
> 直觉上应该有效果的，不过要先确保继续预训练后的模型比之前的好，再迁移到这个任务上。

1.我做了实验，在哈工大那个chinese-bert-wwm-ext基础上做了增量预训练，实验结果是在cner数据集上与原始bert相比F1下降了0.2，在我的铁路数据集上F1提高了0.7，实验还算成功，也算验证了Don't Stop Pretraining: Adapt Language Models to Domains and Tasks这篇文章的观点吧。
2.我还有一个问题，您这个模型，在做fine-tuning时，是固定bert模型内部参数，只调分类器参数，还是bert和分类器参数一起调呢？

**Comment by 943433536** [comment]
> > > > 您好，我想对铁路领域的文本进行实体识别，由于铁路语料与通用语料差距较大，首先使用大量铁路领域无标注的文本对bert模型进行继续预训练。再将这个新得到的bert模型应用于bert-bilstm-crf模型中，是否会提高模型在铁路领域有标注的语料上的精度呢？
> > > 
> > > 
> > > 直觉上应该有效果的，不过要先确保继续预训练后的模型比之前的好，再迁移到这个任务上。
> > 
> > 
> > 1.我做了实验，在哈工大那个chinese-bert-wwm-ext基础上做了增量预训练，实验结果是在cner数据集上与原始bert相比F1下降了0.2，在我的铁路数据集上F1提高了0.7，实验还算成功，也算验证了Don't Stop Pretraining: Adapt Language Models to Domains and Tasks这篇文章的观点吧。 2.我还有一个问题，您这个模型，在做fine-tuning时，是固定bert模型内部参数，只调分类器参数，还是bert和分类器参数一起调呢？
> 
> 一起训练的，注意差分学习率，crf层的学习率一般要比bert层大一些。

嗯嗯，谢谢您
