### ISSUE TITLE
训练自己的数据，内存占用一直增长，直到吃满内存

### ISSUE THREAD

**Issue by ykallan** [taishan1994/pytorch_bert_bilstm_crf_ner#44]
使用自己的数据进行训练，处理为bio，bme，bios等多个格式，在加载数据的时候，内存占用一直增长，最后卡死电脑，只能强行重启，不知道应该怎么处理。最开始以为是数据量太大的问题，训练集使用2w数据，也会出现这种情况。

**Comment by taishan1994** [comment]
> 使用自己的数据进行训练，处理为bio，bme，bios等多个格式，在加载数据的时候，内存占用一直增长，最后卡死电脑，只能强行重启，不知道应该怎么处理。最开始以为是数据量太大的问题，训练集使用2w数据，也会出现这种情况。

从mid_data到得到final_data下的数据是没问题的吗？

**Comment by ykallan** [comment]
> > 使用自己的数据进行训练，处理为bio，bme，bios等多个格式，在加载数据的时候，内存占用一直增长，最后卡死电脑，只能强行重启，不知道应该怎么处理。最开始以为是数据量太大的问题，训练集使用2w数据，也会出现这种情况。
> 
> 从mid_data到得到final_data下的数据是没问题的吗？

运行转换是没有问题的，没有任何异常显示，训练数据在家里，可能需要晚上才能再看一下
