### ISSUE TITLE
> 我加你qq吧，你说下。

### ISSUE THREAD

**Issue by mzbqhbc** [taishan1994/pytorch_bert_bilstm_crf_ner#46]
> 我加你qq吧，你说下。

2446642294

_Originally posted by @SkylerMa in https://github.com/taishan1994/pytorch_bert_bilstm_crf_ner/issues/2#issuecomment-905421819_
           这个到底是啥原因？ 模型错误？

**Comment by taishan1994** [comment]
> ```
>           > 我加你qq吧，你说下。
> ```
> 
> 2446642294
> 
> _Originally posted by @SkylerMa in [#2 (comment)](https://github.com/taishan1994/pytorch_bert_bilstm_crf_ner/issues/2#issuecomment-905421819)_ 这个到底是啥原因？ 模型错误？

可能后面重构了，自己训练个，不要使用之前的了。

**Comment by mzbqhbc** [comment]
已经解决了  谢谢
