### ISSUE TITLE
关于使用CRF文件将BERT+CRF模型转换为ONNX的问题

### ISSUE THREAD

**Issue by colabpp** [taishan1994/pytorch_bert_bilstm_crf_ner#47]
在训练并将BERT+CRF模型转换为ONNX模型时，我们应该使用哪个CRF文件？根据README，我们必须使用这个文件[pytext-crf](https://github.com/facebookresearch/pytext/blob/main/pytext/models/crf.py)，那么我们是否必须对其进行一些修改才能使其发挥作用？

**Comment by taishan1994** [comment]
> 在训练并将BERT+CRF模型转换为ONNX模型时，我们应该使用哪个CRF文件？根据README，我们必须使用这个文件[pytext-crf](https://github.com/facebookresearch/pytext/blob/main/pytext/models/crf.py)，那么我们是否必须对其进行一些修改才能使其发挥作用？

convert_onnx下已经有修改好的模型了，直接设置convert_onnx.py里面的相关参数配置运行就可以了。

**Comment by colabpp** [comment]
谢谢你的快速回复。我们应该使用哪种CRF代码将BERT-CRF模型转换为ONNX，是[pytorch-crf](https://pytorch-crf.readthedocs.io/en/stable/)还是README中提到的[layers/CRF.py](https://github.com/taishan1994/pytorch_bert_bilstm_crf_ner/blob/main/layers/CRF.py)或[pytext/crf](https://github.com/facebookresearch/pytext/blob/main/pytext/models/crf.py)中提供的代码？
`原本的pytorch-crf不能转换为onnx，这里使用了here`

**Comment by taishan1994** [comment]
> 谢谢你的快速回复。我们应该使用哪种CRF代码将BERT-CRF模型转换为ONNX，是[pytorch-crf](https://pytorch-crf.readthedocs.io/en/stable/)还是README中提到的[layers/CRF.py](https://github.com/taishan1994/pytorch_bert_bilstm_crf_ner/blob/main/layers/CRF.py)或[pytext/crf](https://github.com/facebookresearch/pytext/blob/main/pytext/models/crf.py)中提供的代码？ `原本的pytorch-crf不能转换为onnx，这里使用了here`

convert_onnx用的其下面的convert_onnx/bert_ner_model_onnx.py里面的模型，里面使用的是from layers.CRF import CRF

**Comment by colabpp** [comment]
我已经开始工作了，pytorch的版本有问题。谢谢你的工作和支持。你是伟大的!

**Comment by libaiCool** [comment]
你好，convert_onnx.py导出的onnx模型无法支持多条数据并行推理。报错如下：
best_tags_list[:, i + 1] = history[i, :, last_idx].squeeze(1)
RuntimeError: shape mismatch: value tensor of shape [2, 2] cannot be broadcast to indexing result of shape [2]
请问该如何处理

**Comment by taishan1994** [comment]
因为CRF的原因，不能进行batch推理
