### ISSUE TITLE
更改时的相关问题

### ISSUE THREAD

**Issue by iamshujie** [taishan1994/pytorch_bert_bilstm_crf_ner#6]
我想请问下，
1、该怎么用自己的训练数据训练模型，应该替换哪个文件。如何运行是训练模型，如何是用模型进行识别。
2、mid_data下json文件里的格式我不是很懂，train和test这些格式是用来做啥的，我是否需要进行更改。
3、##This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Load ckpt from ./checkpoints/bert_crf/model.pt ##这个报错请问是否需要关注解决？
十分感谢！

**Comment by taishan1994** [comment]
> 我想请问下， 1、该怎么用自己的训练数据训练模型，应该替换哪个文件。如何运行是训练模型，如何是用模型进行识别。 2、mid_data下json文件里的格式我不是很懂，train和test这些格式是用来做啥的，我是否需要进行更改。 3、##This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model). Load ckpt from ./checkpoints/bert_crf/model.pt ##这个报错请问是否需要关注解决？ 十分感谢！

1、要训练自己数据，需要处理数据为mid_data下的*.json的那种格式。你看preprocess.py里面的处理逻辑。
2、bertForNer.train()、bertForNer.test()、bertForNer.predict()分别是训练、测试和预测。
3、加载模型不报错就没有问题。

**Comment by iamshujie** [comment]
十分感激楼主，给我的建议十分有用，为楼主点赞

**Comment by iamshujie** [comment]
十分感激楼主，楼主的建议对我十分有帮助。给楼主点赞。
