### ISSUE TITLE
在执行convert_onnx.py时出现异常

### ISSUE THREAD

**Issue by tjulh** [taishan1994/pytorch_bert_bilstm_crf_ner#61]
作者你好，我在执行你的convert_onnx.py将模型转为onnx时，有warning如下
![图片](https://github.com/taishan1994/pytorch_bert_bilstm_crf_ner/assets/24493479/4d229638-1fd3-4ee3-9caf-3933795a6873)
生成的onnx文件很小，也无法加载推理

**Comment by taishan1994** [comment]
把torch.tensor()去掉看看

**Comment by tjulh** [comment]
> 把torch.tensor()去掉看看

解决了，看到你的readme里面有说CRF需要换掉
