### ISSUE TITLE
pytorch 版本使用  torch-2.1.0+cu121-cp38-cp38-win_amd64.whl 可以吗？

### ISSUE THREAD

**Issue by icefoxhz** [taishan1994/pytorch_bert_bilstm_crf_ner#69]
pytorch 版本使用 torch-2.1.0+cu121-cp38-cp38-win_amd64.whl 可以吗？

**Comment by icefoxhz** [comment]
pytorch 版本使用 torch-2.1.0+cu121-cp38-cp38-win_amd64.whl 可以吗？

**Comment by taishan1994** [comment]
torch版本应该影响不是特别大。
