### ISSUE TITLE
关于stack expects a non-empty TensorList的问题，又要叨扰下作者。

### ISSUE THREAD

**Issue by iamshujie** [taishan1994/pytorch_bert_bilstm_crf_ner#8]
首先十分感谢楼主的耐心解答，真的是让我在学习代码的路上感受到了前辈温暖（泪）。
我在训练的时候，将train的注释去掉，并且已经用raw_data下的程序生成了mid_data中的json文件，又用preprocess.py运行处理成功，生成pkl文件，进行train的时候报错**##RuntimeError: stack expects a non-empty TensorList。**
我进行了多次调试，自己的理解应该是**“total_norm = torch.norm(torch.stack([torch.norm(p.grad.detach(), norm_type) for p in parameters]), norm_type)”“torch.nn.utils.clip_grad_norm_(self.model.parameters(), self.args.max_grad_norm)”** 这几句出现了问题，但是我在解决它的时候无从下手，不知道到底是数据的哪一步出现了问题，还是我的操作有问题，真的是有些崩溃。上网查询的感觉是tensor中的数据没有正确传入（但是我并不是很理解啥意思，以及怎么修改）。
昨天我将您的源代码也就是没经过我更改的代码运行下想看看能否找到些头绪，但是也报出了同样的错误。
所以我想请教下楼主，您在运行的时候是否碰到过这个问题，是如何解决的，还是说我的操作又出现了问题。
再次感谢楼主！

**Comment by iamshujie** [comment]
```
> E:\env\py7\lib\site-packages\transformers\optimization.py:309: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use thePyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
>   `FutureWarning,`
> Traceback (most recent call last):
>   File "F:/pytorch_bert_bilstm_crf_ner-main/pytorch_bert_bilstm_crf_ner-main/main.py", line 214, in <module>
>     bertForNer.train()
>   File "F:/pytorch_bert_bilstm_crf_ner-main/pytorch_bert_bilstm_crf_ner-main/main.py", line 46, in train
>     torch.nn.utils.clip_grad_norm_(self.model.parameters(), self.args.max_grad_norm)
>   File "E:\env\py7\lib\site-packages\torch\nn\utils\clip_grad.py", line 31, in clip_grad_norm_
>     total_norm = torch.norm(torch.stack([torch.norm(p.grad.detach(), norm_type) for p in parameters]), norm_type)
> RuntimeError: stack expects a non-empty TensorList

> 
```
这是我运行出来的错误

**Comment by taishan1994** [comment]
> ```
> > E:\env\py7\lib\site-packages\transformers\optimization.py:309: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use thePyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
> >   `FutureWarning,`
> > Traceback (most recent call last):
> >   File "F:/pytorch_bert_bilstm_crf_ner-main/pytorch_bert_bilstm_crf_ner-main/main.py", line 214, in <module>
> >     bertForNer.train()
> >   File "F:/pytorch_bert_bilstm_crf_ner-main/pytorch_bert_bilstm_crf_ner-main/main.py", line 46, in train
> >     torch.nn.utils.clip_grad_norm_(self.model.parameters(), self.args.max_grad_norm)
> >   File "E:\env\py7\lib\site-packages\torch\nn\utils\clip_grad.py", line 31, in clip_grad_norm_
> >     total_norm = torch.norm(torch.stack([torch.norm(p.grad.detach(), norm_type) for p in parameters]), norm_type)
> > RuntimeError: stack expects a non-empty TensorList
> 
> > 
> ```
> 
> 这是我运行出来的错误

你把训练注释掉之前是否已经训练好模型了，然后也正确加载了模型。

**Comment by iamshujie** [comment]
不知道我理解的对不对，您是指最后在final_data里生成pkl文件吗，这个我已经生成。程序中的read_pkl也能够读取。训练的模型不应该是经过bertForNer.train()才能生成吗？

**Comment by taishan1994** [comment]
> 不知道我理解的对不对，您是指最后在final_data里生成pkl文件吗，这个我已经生成。程序中的read_pkl也能够读取。训练的模型不应该是经过bertForNer.train()才能生成吗？

可以预先处理，也可以在训练中生成，先生成pkl是为了避免每次都要重新处理耗时

**Comment by zllearn** [comment]
我今天也出现了这种错误，最后我把所有的输出形状都打印了出来，发现最后一个batch_size的大小为1，所以导致了这种错误，只要把dataloader的drop_last设置为True，就能正常运行了

**Comment by iamshujie** [comment]
十分感谢，您说办法很有效，batch_size的大小对于能否成功运行很重要

**Comment by chahu-12** [comment]
> drop_last
都设置成True了，为什曼还会这样的错误呢

**Comment by zllearn** [comment]
您好，有具体的报错信息吗




张乐
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "taishan1994/pytorch_bert_bilstm_crf_ner"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月9日(星期一) 晚上11:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [taishan1994/pytorch_bert_bilstm_crf_ner] 关于stack expects a non-empty TensorList的问题，又要叨扰下作者。 (Issue #8)





  
drop_last
 都设置成True了，为什曼还会这样的错误呢
